spring.application.name=task-tracker-email-sender

spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer
spring.kafka.consumer.group-id=email-sender
spring.kafka.consumer.properties[spring.json.use.type.headers]=false
spring.kafka.consumer.properties[spring.json.value.default.type]=ru.prplhd.tasktracker.emailsender.message.EmailSendingTask

application.mail.from=task-tracker@sandbox-8311026-3a287c.unigosendbox.com

spring.mail.host=smtp.go2.unisender.ru
spring.mail.port=587
spring.mail.username=${SMTP_USERNAME}
spring.mail.password=${SMTP_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true